# Generated by Django 3.0.3 on 2020-03-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_name', models.CharField(max_length=50, verbose_name='short name')),
                ('position', models.CharField(max_length=255, verbose_name='position')),
                ('imageUrl', models.URLField(verbose_name='image url')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('place', models.CharField(max_length=255, verbose_name='place')),
                ('teacher', models.CharField(max_length=255, verbose_name='teacher')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('weekDay', models.PositiveSmallIntegerField(verbose_name='week day')),
                ('appointment_id', models.UUIDField(verbose_name='appointment id')),
                ('service_id', models.UUIDField(verbose_name='service id')),
                ('pay', models.BooleanField(default=False, verbose_name='pay')),
                ('appointment', models.BooleanField(default=False, verbose_name='appointment')),
                ('color', models.CharField(max_length=7, verbose_name='color')),
                ('availability', models.SmallIntegerField(verbose_name='availability')),
                ('teacher_v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='fitness_app.Teacher', verbose_name='teacher v2')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
    ]
